# Generated by Django 4.2.2 on 2023-06-20 16:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_email_profile_relationship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('caption', models.TextField(default='caption...')),
                ('image', models.ImageField(blank=True, upload_to='post_images')),
                ('created_at', models.DateTimeField(blank=True, verbose_name=datetime.datetime(2023, 6, 20, 17, 12, 6, 824698))),
                ('no_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(blank=True, default='media/profile_images/user_318-804790.jpg', upload_to='profile_images'),
        ),
    ]
