# Generated by Django 4.2.2 on 2023-06-20 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_alter_profile_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2023, 6, 20, 17, 23, 7, 918875)),
        ),
    ]
