# Generated by Django 4.2.2 on 2023-06-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_follow_remove_comment_user_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='friend',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='poster',
            new_name='user',
        ),
    ]
